# More comprehensive example
repo:
  - '*'         # All files in the root directory
  - '!*.md'     # Exclude markdown files

documentation:
  - '**/*.md'   # All markdown files in any directory
  - 'docs/**/*' # Everything in the docs directory
