name: test1
run-name: test1 ${{ github.event_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
      - release/*
    paths:
      - doc/**
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "hello"
      - name: step2 - checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: step3 - list
        run: |
          echo "tree listing of ${{ github.repository }}"
          tree
